LOG_DIR = ${DORIS_HOME}/log

JAVA_OPTS_FOR_JDK_17="-Djavax.security.auth.useSubjectCredsOnly=false -Xss4m -Xmx2048m -XX:+UseG1GC -Xlog:gc*:${LOG_DIR}/fe.gc.log.$DATE:time"

sys_log_level = INFO

# Network
priority_networks = 0.0.0.0/0
http_port = 8030
rpc_port = 9020
query_port = 9030
edit_log_port = 9010
mysql_service_nio_enabled = true

# Single replica for laptop demo
default_replication_num = 1
min_load_replica_num = 1

enable_http_server_v2 = true

# Allow user creation/large queries
qe_max_connection = 1024
max_running_txn_num_per_db = 1000
